FROM golang:1.13-alpine3.10 as build
ENV GO111MODULE=on
WORKDIR /go/src/app
COPY . .
RUN apk add --no-cache --update build-base git && \
    GOOS=linux GOARCH=__GOLANG_ARCH__ make build

FROM __BASEIMAGE_ARCH__/alpine:3.10
COPY --from=build /go/src/app/mysensorsbootloader2mqtt /usr/local/bin/mysensorsbootloader2mqtt
CMD ["mysensorsbootloader2mqtt"]
