FROM golang:1.11-alpine3.8 as build
ENV GO111MODULE=on
WORKDIR /go/src/app
COPY . .
RUN apk add --no-cache --update build-base git && \
    GOOS=linux GOARCH=__GOLANG_ARCH__ make build

FROM __BASEIMAGE_ARCH__/alpine:3.8
COPY --from=build /go/src/app/mysb /usr/local/bin/mysb
VOLUME /config
CMD ["mysb", "-c", "/config/config.yaml"]
