FROM golang:1.11-alpine3.8 as build
COPY . /go/src/app
RUN apk add --no-cache --update build-base git && \
    cd /go/src/app/ && \
    make clean && \
    GOOS=linux GOARCH=__GOLANG_ARCH__ make && \
    if [[ -f bin/mysb ]]; then mkdir -p bin/linux___GOLANG_ARCH__ && mv bin/mysb bin/linux___GOLANG_ARCH__; fi;

FROM __BASEIMAGE_ARCH__/alpine:3.8
COPY --from=build /go/src/app/bin/linux___GOLANG_ARCH__/mysb /usr/local/bin/mysb
VOLUME /config
CMD ["mysb", "-c", "/config/config.yaml"]
