// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/mannkind/twomqtt"
)

// Injectors from wire.go:

func initialize() *sink {
	mainOpts := newOpts()
	mainSinkOpts := mainOpts.Sink
	mqttOpts := mainSinkOpts.MQTTOpts
	mqtt := twomqtt.NewMQTT(mqttOpts)
	mainSink := newSink(mqtt, mainSinkOpts)
	return mainSink
}
