// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

// Injectors from wire.go:

func InitializeMysb() *Mysb {
	config := NewConfig()
	mqttFuncWrapper := NewMQTTFuncWrapper()
	mysb := NewMysb(config, mqttFuncWrapper)
	return mysb
}
